name: WarpPortals
version: 4.3.0.3

main: com.mccraftaholics.warpportals.bukkit.PortalPlugin
softdepend: [WorldGuard, Multiverse-Core, Multiverse, Multiworld, My Worlds]

commands:
  wp:
    description: List all WarpPortal related commands
    usage: /wp
    aliases: [phelp, wp-help]
    permissions: warpportals.listcommands
  wp-portal-create:
    description: Bind the WarpPortal Creation tool to the current item
    usage: /wp-portal-create [portalname] [destName|(World,x,y,z)] [portalMaterial]
    aliases: [pcreate, wppc]
    permissions: warpportals.admin.portal.create
  wp-portal-material:
    description: Change a WarpPortal's block type to another material
    usage: /wp-portal-material [portalname] [portalMaterial]
    aliases: [wppm]
    permissions: warpportals.admin.portal.material
  wp-portal-delete:
    description: Delete a WarpPortal by name.
    usage: /wp-portal-delete [portalName]
    aliases: [pdelete, wppd]
    permissions: warpportals.admin.portal.delete.command
  wp-portal-deltool:
    description: Bind the Portal Deletion tool to the current item
    usage: /wp-portal-deltool
    aliases: [pdeltool, wppdt]
    permissions: warpportals.admin.portal.delete.tool
  wp-portal-list:
    description: List all WarpPortals
    usage: /wp-portal list
    aliases: [plist, wp-portals, wppl]
    permissions: warpportals.admin.portal.list
  wp-portal-teleport:
    description: Teleport to a WarpPortal
    usage: /wp-portal-teleport [portalName]
    aliases: [wp-portal-tp, wpptp]
    permissions: warpportals.admin.portal.teleport
  wp-destination-create:
    description: Create a WarpPortal Location using your current location and point-of-view
    usage: /wp-destination-create [destinationName]
    aliases: [pdest, wpdc, wp-dest-create]
    permissions: warpportals.admin.destination.create
  wp-destination-delete:
    description: Remove a WarpPortal Destination by name
    usage: /wp-destination-delete [destinationName]
    aliases: [pdestdel, wpdd, wp-dest-delete]
    permissions: warpportals.admin.destination.delete
  wp-destination-list:
    description: List all saved WarpPortal Destinations
    usage: /wp-destination-list
    aliases: [pdestlist, wp-destinations, wp-dest-list, wpdl, wp-dests]
    permissions: warpportals.admin.destination.list
  wp-destination-teleport:
    description: Teleport to a WarpPortal Destination
    usage: /wp-destination-teleport [destinationName]
    aliases: [wp-destination-tp, wp-dest-tp, wp-dest-teleport, wpdtp]
    permissions: warpportals.admin.destination.teleport
  wp-save:
    description: Force save all WarpPortal data
    usage: /wp-save
    aliases: [psave, wps]
    permissions: warpportals.admin.op.save
  wp-load:
    description: Force load WarpPortal data from portals.yml
    usage: /wp-load
    aliases: [pload, wpl]
    permissions: warpportals.admin.op.load
  wp-backup:
    description: Backup the current WarpPortal data to "portals.yml_yyyy-MM-ddTkk-mm-ss.bac"
    usage: /wp-backup
    aliases: [pbackup, wpb]
    permissions: warpportals.admin.op.backup

permissions:
  warpportal.admin:
    description: Gives access to all WarpPortal commands
    default: op
  warpportal.enter:
    description: Allows a player to travel through Warp Portals
    default: true
  warpportal.admin.breakblock:
    description: Allows a player to break blocks within a WarpPortal
    default: false